### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by maxleistner** [WalkingPizza/strapi-plugin-shopify-fields#4]
I did everything exactly like in the ReadMe. After that i added a Collection Type and added a custom field for single Product. If i try to add it i get a 500error and this message: 

![Bildschirmfoto 2023-01-10 um 12 20 37](https://user-images.githubusercontent.com/7567185/211537968-4865922c-89a7-45d8-aff0-f4b9e9ec7a47.png)

```
[2023-01-10 11:18:25.192] error: getaddrinfo ENOTFOUND https://****.myshopify.com
RequestError: getaddrinfo ENOTFOUND https://****.myshopify.com
    at ClientRequest.<anonymous> (/var/www/****/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.origin.emit (/var/www/****/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
```

A documentation on how to set up the Collection/Single Types would be great as well :)

**Comment by maxleistner** [comment]
found the solution on my own after checking.... 
no https:// ;)
